### ISSUE TITLE
refactor_user

### ISSUE THREAD

**Issue by polyakovigor** [capitalsav/rails_chat#26]
- [x] add new fields: `first_name`, `last_name`, `display_name` and remove unnecessary fields
- [x] remove `elasticsearch` stuff (unneeded)
- [x] remove 'omniauth` stuff (unneeded)
- [x] add devise `confirmable` module
- [x] add gem `letter_openner` for check confirm email

**Comment by capitalsav** [comment]
Merged. Closed.
