### ISSUE TITLE
refactor_clean_assets_webpacker_user_workspace

### ISSUE THREAD

**Issue by vladfreel** [capitalsav/rails_chat#51]
- [x] Delete useless style files in app/assets/stylesheets 
- [x] Delete useless js and coffee files in app/assets/javascripts
- [x] Delete images from app/assets/images
- [x] Delete user_workspace_controller and user_workspace_helper
- [x] Delete unneeded scss files from socket_chat/app/javascript/style:

- auth.scss
- users.scss
- home.scss
- main.scss

**Comment by polyakovigor** [comment]
also, delete unneeded scss files from `socket_chat/app/javascript/style`:

- auth.scss
- users.scss
- home.scss
- main.scss

**Comment by capitalsav** [comment]
@vladfreel @polyakovigor  I have updated issue description.
